apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-reves-bleus
  namespace: domaine-des-reves-bleus
spec:
  selector:
    matchLabels:
      app: cloudflared-reves-bleus
  template:
    metadata:
      labels:
        app: cloudflared-reves-bleus
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --no-autoupdate
        - run
        - --token
        - "YOUR_CLOUDFLARE_TUNNEL_TOKEN_HERE"
