apiVersion: v1
kind: Service
metadata:
  name: domaine-des-reves-bleus-frontend-service
  namespace: domaine-des-reves-bleus
spec:
  selector:
    app: domaine-des-reves-bleus-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: domaine-des-reves-bleus-frontend
  namespace: domaine-des-reves-bleus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: domaine-des-reves-bleus-frontend
  template:
    metadata:
      labels:
        app: domaine-des-reves-bleus-frontend
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d/
          readOnly: true
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
      volumes:
      - name: config
        hostPath:
          path: /home/zozoo/Domaine_des_reves_bleus/Frontend/nginx
          type: Directory
      - name: html
        hostPath:
          path: /home/zozoo/Domaine_des_reves_bleus/Frontend/dist
          type: Directory
