apiVersion: v1
kind: Service
metadata:
  name: domaine-des-reves-bleus-backend-service
  namespace: domaine-des-reves-bleus
spec:
  selector:
    app: domaine-des-reves-bleus-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: domaine-des-reves-bleus-backend
  namespace: domaine-des-reves-bleus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: domaine-des-reves-bleus-backend
  template:
    metadata:
      labels:
        app: domaine-des-reves-bleus-backend
    spec:
      containers:
      - name: backend
        image: domaine-des-reves-bleus-backend:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "100m"      
            memory: "200Mi"  
          limits:
            cpu: "250m"      
            memory: "512Mi"  
        ports:
        - containerPort: 8000
        workingDir: /app
        volumeMounts:
        - name: backend
          mountPath: /app
          readOnly: false
        - name: uploads
          mountPath: /app/uploads
          readOnly: false
        env:
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: domaine-des-reves-bleus-secrets
              key: stripe-secret-key
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: domaine-des-reves-bleus-secrets
              key: stripe-webhook-secret
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: domaine-des-reves-bleus-secrets
              key: jwt-secret
        - name: MARIADB_HOST
          valueFrom:
            secretKeyRef:
              name: domaine-des-reves-bleus-secrets
              key: mariadb-host
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: domaine-des-reves-bleus-secrets
              key: mariadb-user
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: domaine-des-reves-bleus-secrets
              key: mariadb-password
        - name: MARIADB_DATABASE
          valueFrom:
            secretKeyRef:
              name: domaine-des-reves-bleus-secrets
              key: mariadb-database
        - name: FRONTEND_URL
          value: "https://domainedesrevesbleus.eu"
        - name: PORT
          value: "8000"
      volumes:
      - name: backend
        hostPath:
          path: /home/zozoo/Domaine_des_reves_bleus/Backend
          type: Directory
      - name: uploads
        hostPath:
          path: /home/zozoo/Domaine_des_reves_bleus/Backend/uploads
          type: Directory