apiVersion: v1
kind: Service
metadata:
  name: domaine-des-reves-bleus-frontend-service
  namespace: domaine-des-reves-bleus
spec:
  selector:
    app: domaine-des-reves-bleus-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: domaine-des-reves-bleus-frontend
  namespace: domaine-des-reves-bleus
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: domaine-des-reves-bleus-frontend
  template:
    metadata:
      labels:
        app: domaine-des-reves-bleus-frontend
    spec:
      containers:
      - name: nginx
        image: domaine-des-reves-bleus-front:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10