apiVersion: v1
kind: Secret
metadata:
  name: domaine-des-reves-bleus-secrets
  namespace: domaine-des-reves-bleus
type: Opaque
stringData:
  stripe-secret-key: "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"
  stripe-webhook-secret: "whsec_5a57b21f8655fcd5b89f79dbf322c6a62b9d992eca5effe6ab85e09b795672b8"
  jwt-secret: "e2856de147b6de8b87f059054378965db677f03d326d7a9f98c0ba4b52e886d37a3d4099153a43c999710b31f2ebbe411f896b04c9ce33315d4d5c57681dd608"
  mariadb-host: "192.168.1.32"
  mariadb-user: "revesbleus"
  mariadb-password: "8osFwIk*A9^SR9@1"
  mariadb-database: "DRB"
  jwt-private-key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDGP0gb/SxV65el
    KLoYmUqhenA1B/ixB2aRcJG6EW8viztSF9F1C1lt8MZeG5r01zTuECaUxSUilWEy
    WjsNLA0B7+eAOImsUYt3anKjb+LMox2wPmi7dhawuobWLfMz5c3R1Q8fDCkXGZuf
    xTK4f0e/2elol7AvfDZ7cZnuPgellXUjrhVGUGXFE9urp2dKnHu+aY/9gJ1z5t7/
    7yzvMtvXtBaBoKe3LTBYnejwjmlZBDSjFw+6EIOnQvMYxXh+Da6h/I9Mbf0Znecz
    5opavikkoL3rKqq+BB0c9Ge4B2Xu8hsG6BUPMAemRpMRVyoHwoeAFP6LEAXgrFQr
    uVCc3B2nAgMBAAECggEAHxqMoL+PC4f5dJM4PLsdnMo4p/QGjm01KCUmPVrrkTpi
    EJY7abFh0ur6Odz7lJCIoGqY8wcfYBavIkGf5DLWHkiv5KEk5eFWurdRIdgLGG+Q
    goy4Io6mLreFMj4RW0Ih5wXA5+52Kpv88QtKfZc9VZobPIAYHMsl7SY8sBwRV7wd
    b7jlneN8kt7x5+s8F2KR8i0yTcUNqzl7XkcabcKkuNHoV6LPFwSNERCl8pAZwp3A
    kHKZLVEj5Ay3624X1u4V5/cHNfwVuQChpl+lDBNnRsQfBOZB/J041HAIDJ8mL4Rw
    dl8QVsUpLhhHWbckIq6rq97eMw7Njytuzr7879LZeQKBgQDwu0NhcCLa5HUQTE00
    p1gD2IJiNmy238EVOkGG4W5zj3CXr30VZFLExV3XUrtapsWumk/X8ZPF/9D1J3ZQ
    ae9sxqMilk6Ukd5l1vZxr13CgUqaTAw2lmMiDFQx64q7PgxLa6DLvsPTg2nMHNMX
    JIsP5MdTqPHyFRIvy3he0IevTQKBgQDS0jRX/yXJua9ZJelKESvrfkDDXC+KyNnY
    e+nECqL95NNfHQRsgmHiEeaFo9CtA/fz1W2W6J8aF5mHfshIS3l79QDUBHEHONcm
    TDdf36yRo6zWCrE7rMGvNkgtt0LtTInkN75TlYylUfkMlYeWhdUjzmU1yS/pxQ3s
    HumJ7qjuwwKBgGr/QMapOcTC8EkrMNGrY5JqBCG1AQMTVtWhjAhwYFBau/efl2AP
    tD4jXz9aVU3IfGrLyZs4k67Ysj6UqKC7RSC69T1lQ04Du67WKbmD8Y+HOep0zKTi
    mPNEOZPqlkH9JSfMka6dfpqfeUGwuh46LtkEnZfQqqEnvmqh7EFwPC6tAoGAOi+a
    Es9w9oQxSUGVacPjg1ONPF4tIPjeZ0mL83ecFMcbL50qo2g469RU832LErWNsdau
    MIBzqRfqX+M2E/4AwZ2VZO704zFk8EUI44Uwc+HgyhKZaAb+TgWFVljGOAhv5nUc
    KqWT8+zz9+0tRvYZJZDJjlbAypyAgzLk8hTUu1ECgYEA0JYiXqgUztEMOg9DZZlq
    +9gWDQUcFypyidi4g+4aci184/Oe0wBPxor+tcr3lW1cBElMNZ7HS9oNnErHU/R1
    z/tGDWeJn1Euw5qokqnkpzEgN7rqcCZPqNM6oBMxfcsnSjXtNp1xMvvY8EmuI+3D
    KlI1pjk+eQFBd+NbJJBpwf4=
    -----END RSA PRIVATE KEY-----
  jwt-public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxj9IG/0sVeuXpSi6GJlK
    oXpwNQf4sQdmkXCRuhFvL4s7UhfRdQtZbfDGXhua9Nc07hAmlMUlIpVhMlo7DSwN
    Ae/ngDiJrFGLd2pyo2/izKMdsD5ou3YWsLqG1i3zM+XN0dUPHwwpFxmbn8UyuH9H
    v9npaJewL3w2e3GZ7j4HpZV1I64VRlBlxRPbq6dnSpx7vmmP/YCdc+be/+8s7zLb
    17QWgaCnty0wWJ3o8I5pWQQ0oxcPuhCDp0LzGMV4fg2uofyPTG39GZ3nM+aKWr4p
    JKC96yqqvgQdHPRnuAdl7vIbBugVDzAHpkaTEVcqB8KHgBT+ixAF4KxUK7lQnNwd
    pwIDAQAB
    -----END PUBLIC KEY-----

