apiVersion: v1
kind: Service
metadata:
  name: domaine-des-reves-bleus-frontend-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "drb.labels" . | nindent 4 }}
    {{- include "drb.frontend.selectorLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "drb.frontend.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80                              # port exposé au cluster / Ingress
      targetPort: {{ .Values.frontend.port }} # port réel du pod (8080, non-root)
