apiVersion: v1
kind: Service
metadata:
  name: domaine-des-reves-bleus-frontend-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "drb.labels" . | nindent 4 }}
    {{- include "drb.frontend.selectorLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "drb.frontend.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
